using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MunicipalServicesApp
{

    // Creating sample events(I could possibly use and API for this lol )
    public class SampleDataProvider
    {
        public static List<Event> GetSampleEvents()
        {
            return new List<Event>
            {
                new Event("Community Meeting", "Community", new DateTime(2024, 12, 10)),
                new Event("Music Concert", "Music", new DateTime(2024, 11, 22)),
                new Event("Soccer Tournament", "Sports", new DateTime(2024, 10, 15)),
                new Event("Art Exhibition", "Culture", new DateTime(2024, 11, 5)),
                new Event("Tech Meetup", "Technology", new DateTime(2024, 12, 1)),
                new Event("Farmers Market", "Community", new DateTime(2024, 10, 20)),

                    new Event("Music Concert", "Music", new DateTime(2024, 11, 22)),

                    new Event("Soccer Tournament", "Sports", new DateTime(2024, 10, 15)),
                    new Event("Art Exhibition", "Art", new DateTime(2024, 12, 01)),
                    new Event("Tech Conference", "Technology", new DateTime(2024, 11, 05)),
                    new Event("Charity Run", "Sports", new DateTime(2024, 10, 18)),
                    new Event("Food Festival", "Food", new DateTime(2024, 12, 08)),
                    new Event("Science Fair", "Education", new DateTime(2024, 11, 28)),
                    new Event("Literature Workshop", "Education", new DateTime(2024, 10, 21)),
                    new Event("Film Festival", "Entertainment", new DateTime(2024, 12, 15)),
                    new Event("Yoga Retreat", "Health", new DateTime(2024, 11, 11)),
                    new Event("Cycling Marathon", "Sports", new DateTime(2024, 10, 20)),
                    new Event("Networking Event", "Business", new DateTime(2024, 12, 12)),
                    new Event("Dance Competition", "Entertainment", new DateTime(2024, 11, 17)),
                    new Event("Gardening Workshop", "Lifestyle", new DateTime(2024, 10, 27)),
                    new Event("Job Fair", "Business", new DateTime(2024, 12, 03)),

                    new Event("Fishing Tournament", "Recreation", new DateTime(2024, 11, 23)),
                    new Event("Cooking Class", "Food", new DateTime(2024, 10, 13)),
                    new Event("Stand-up Comedy Night", "Entertainment", new DateTime(2024, 12, 19)),
                    new Event("Meditation Workshop", "Health", new DateTime(2024, 11, 09)),
                    new Event("Dog Show", "Recreation", new DateTime(2024, 10, 22)),
                    new Event("Photography Contest", "Art", new DateTime(2024, 12, 05)),

                    new Event("Fishing Tournament", "Recreation", new DateTime(2024, 11, 23)),
                    new Event("Cooking Class", "Food", new DateTime(2024, 10, 13)),
                    new Event("Stand-up Comedy Night", "Entertainment", new DateTime(2024, 12, 19)),
                    new Event("Meditation Workshop", "Health", new DateTime(2024, 11, 09)),
                    new Event("Dog Show", "Recreation", new DateTime(2024, 10, 22)),
                    new Event("Photography Contest", "Art", new DateTime(2024, 12, 05)),
                    new Event("Marathon", "Sports", new DateTime(2024, 04, 14)),
                    new Event("Wine Tasting", "Food", new DateTime(2024, 05, 18)),
                    new Event("Jazz Festival", "Music", new DateTime(2024, 06, 22)),
                    new Event("Yoga in the Park", "Health", new DateTime(2024, 07, 06)),
                    new Event("Farmers Market", "Food", new DateTime(2024, 08, 03)),
                    new Event("Art Exhibition", "Art", new DateTime(2024, 09, 15)),
                    new Event("Book Fair", "Education", new DateTime(2024, 03, 28)),
                    new Event("Science Fair", "Education", new DateTime(2024, 04, 05)),
                    new Event("Theater Performance", "Entertainment", new DateTime(2024, 05, 11)),
                    new Event("Charity Run", "Sports", new DateTime(2024, 06, 09)),
                    new Event("Food Truck Festival", "Food", new DateTime(2024, 07, 20)),
                    new Event("Classic Car Show", "Recreation", new DateTime(2024, 08, 17)),
                    new Event("Film Festival", "Entertainment", new DateTime(2024, 09, 07)),
                    new Event("Craft Beer Tasting", "Food", new DateTime(2024, 10, 05)),
                    new Event("Halloween Parade", "Entertainment", new DateTime(2024, 10, 31)),
                    new Event("Holiday Market", "Shopping", new DateTime(2024, 12, 07)),
                    new Event("New Year's Eve Fireworks", "Entertainment", new DateTime(2024, 12, 31)),
                    new Event("Winter Carnival", "Recreation", new DateTime(2024, 01, 20)),
                    new Event("Valentine's Day Dance", "Entertainment", new DateTime(2024, 02, 14)),
                    new Event("St. Patrick's Day Parade", "Cultural", new DateTime(2024, 03, 17)),
                    new Event("Easter Egg Hunt", "Family", new DateTime(2024, 03, 31)),
                    new Event("Earth Day Clean-up", "Environment", new DateTime(2024, 04, 22)),
                    new Event("Mother's Day Brunch", "Food", new DateTime(2024, 05, 12)),
                    new Event("Father's Day Barbecue", "Food", new DateTime(2024, 06, 16)),
                    new Event("Independence Day Celebration", "Cultural", new DateTime(2024, 07, 04)),
                    new Event("Summer Music Series", "Music", new DateTime(2024, 07, 13)),
                    new Event("Back to School Fair", "Education", new DateTime(2024, 08, 24)),
                    new Event("Labor Day Picnic", "Recreation", new DateTime(2024, 09, 02)),
                    new Event("Oktoberfest", "Cultural", new DateTime(2024, 09, 21)),
                    new Event("Pumpkin Carving Contest", "Art", new DateTime(2024, 10, 26)),
                    new Event("Veterans Day Ceremony", "Cultural", new DateTime(2024, 11, 11)),
                    new Event("Thanksgiving Community Dinner", "Food", new DateTime(2024, 11, 28)),
                    new Event("Tree Lighting Ceremony", "Cultural", new DateTime(2024, 12, 01)),
                    new Event("Ice Skating Rink Opening", "Recreation", new DateTime(2024, 12, 15)),
                    new Event("Flower Show", "Nature", new DateTime(2024, 05, 25)),
                    new Event("Tech Conference", "Technology", new DateTime(2024, 06, 08)),
                    new Event("Antique Fair", "Shopping", new DateTime(2024, 07, 27)),
                    new Event("Kite Flying Festival", "Recreation", new DateTime(2024, 08, 10)),
                    new Event("Poetry Slam", "Art", new DateTime(2024, 09, 14)),
                    new Event("Salsa Dancing Night", "Entertainment", new DateTime(2024, 10, 19)),
                    new Event("Astronomy Night", "Education", new DateTime(2024, 11, 16)),
                    new Event("Gingerbread House Competition", "Art", new DateTime(2024, 12, 14)),
                    new Event("Volunteer Appreciation Dinner", "Community", new DateTime(2024, 04, 20)),
                    new Event("Job Fair", "Career", new DateTime(2024, 05, 15)),
                    new Event("Pet Adoption Day", "Community", new DateTime(2024, 06, 29)),
                    new Event("Historical Reenactment", "Education", new DateTime(2024, 07, 13)),
                    new Event("Farmers' Appreciation Day", "Community", new DateTime(2024, 08, 31)),
                    new Event("International Food Festival", "Cultural", new DateTime(2024, 09, 28)),
                    new Event("Senior Citizens' Ball", "Community", new DateTime(2024, 10, 12)),
                    new Event("Youth Sports Tournament", "Sports", new DateTime(2024, 11, 02)),

                   
                    // add more events as needed
                    new Event("Tech Conference", "Technology", new DateTime(2024, 06, 08)),
                    new Event("Antique Fair", "Shopping", new DateTime(2024, 07, 27)),
                    new Event("Kite Flying Festival", "Recreation", new DateTime(2024, 08, 10)),
                    new Event("Poetry Slam", "Art", new DateTime(2024, 09, 14)),
                    new Event("Salsa Dancing Night", "Entertainment", new DateTime(2024, 10, 19)),
                    new Event("Astronomy Night", "Education", new DateTime(2024, 11, 16)),
                    new Event("Gingerbread House Competition", "Art", new DateTime(2024, 12, 14)),
                    new Event("Volunteer Appreciation Dinner", "Community", new DateTime(2024, 04, 20)),
                    new Event("Job Fair", "Career", new DateTime(2024, 05, 15)),
                    new Event("Pet Adoption Day", "Community", new DateTime(2024, 06, 29)),
                    new Event("Historical Reenactment", "Education", new DateTime(2024, 07, 13)),
                    new Event("Farmers' Appreciation Day", "Community", new DateTime(2024, 08, 31)),
                    new Event("International Food Festival", "Cultural", new DateTime(2024, 09, 28)),
                    new Event("Senior Citizens' Ball", "Community", new DateTime(2024, 10, 12)),
                    new Event("Youth Sports Tournament", "Sports", new DateTime(2024, 11, 02)),
                    new Event("Tech Conference", "Technology", new DateTime(2024, 06, 08)),
                    new Event("Antique Fair", "Shopping", new DateTime(2024, 07, 27)),
                    new Event("Kite Flying Festival", "Recreation", new DateTime(2024, 08, 10)),
                    new Event("Poetry Slam", "Art", new DateTime(2024, 09, 14)),
                    new Event("Salsa Dancing Night", "Entertainment", new DateTime(2024, 10, 19)),

                    //add more events 

                    new Event("Chess Tournament", "Games", new DateTime(2024, 10, 14)),
                    new Event("Astronomy Night", "Science", new DateTime(2024, 11, 01)),
                    new Event("Community Picnic", "Community", new DateTime(2024, 12, 02)),
                    new Event("Karaoke Night", "Entertainment", new DateTime(2024, 11, 12)),
                    new Event("Coding Bootcamp", "Technology", new DateTime(2024, 10, 24)),
                    new Event("Outdoor Movie Night", "Entertainment", new DateTime(2024, 11, 30)),
                    new Event("Wine Tasting", "Food", new DateTime(2024, 10, 19)),
                    new Event("Marathon", "Sports", new DateTime(2024, 11, 14)),
                    new Event("Baking Competition", "Food", new DateTime(2024, 12, 06)),
                    new Event("Environmental Clean-Up", "Community", new DateTime(2024, 10, 23)),
                    new Event("Board Game Night", "Games", new DateTime(2024, 11, 08)),
                    new Event("Book Club Meeting", "Community", new DateTime(2024, 12, 11)),
                    new Event("Art Class", "Art", new DateTime(2024, 10, 25)),
                    new Event("Robotics Competition", "Technology", new DateTime(2024, 11, 13)),
                    new Event("Acoustic Night", "Music", new DateTime(2024, 12, 14)),
                    new Event("Pottery Workshop", "Art", new DateTime(2024, 10, 29)),
                    new Event("Language Exchange", "Education", new DateTime(2024, 11, 27)),
                    new Event("Theatre Performance", "Entertainment", new DateTime(2024, 12, 20)),
                    new Event("Magic Show", "Entertainment", new DateTime(2024, 10, 30)),
                    new Event("Plant Swap", "Lifestyle", new DateTime(2024, 11, 06)),
                    new Event("Swim Meet", "Sports", new DateTime(2024, 12, 04)),
                    new Event("Fitness Bootcamp", "Health", new DateTime(2024, 10, 26)),
                    new Event("Financial Planning Workshop", "Business", new DateTime(2024, 11, 15)),
                    new Event("Improv Comedy Show", "Entertainment", new DateTime(2024, 12, 07)),
                    new Event("Poetry Slam", "Art", new DateTime(2024, 10, 28)),
                    new Event("STEM Fair", "Education", new DateTime(2024, 11, 29)),
                    new Event("Fishing Tournament", "Recreation", new DateTime(2024, 11, 23)),
                    new Event("Cooking Class", "Food", new DateTime(2024, 10, 13)),
                    new Event("Stand-up Comedy Night", "Entertainment", new DateTime(2024, 12, 19)),
                    new Event("Meditation Workshop", "Health", new DateTime(2024, 11, 09)),
                    new Event("Dog Show", "Recreation", new DateTime(2024, 10, 22)),
                    new Event("Photography Contest", "Art", new DateTime(2024, 12, 05)),
                    new Event("Jazz Festival", "Music", new DateTime(2024, 06, 22)),
                    new Event("Yoga in the Park", "Health", new DateTime(2024, 07, 06)),
                    new Event("Farmers Market", "Food", new DateTime(2024, 08, 03)),
                    new Event("Art Exhibition", "Art", new DateTime(2024, 09, 15)),
                    new Event("Science Fair", "Education", new DateTime(2024, 04, 05)),
                    new Event("Charity Run", "Sports", new DateTime(2024, 06, 09)),
                    new Event("Food Truck Festival", "Food", new DateTime(2024, 07, 20)),
                    new Event("Classic Car Show", "Recreation", new DateTime(2024, 08, 17)),
                    new Event("Film Festival", "Entertainment", new DateTime(2024, 09, 07)),
                    new Event("Craft Beer Tasting", "Food", new DateTime(2024, 10, 05)),
                    new Event("Halloween Parade", "Entertainment", new DateTime(2024, 10, 31)),
                    new Event("Holiday Market", "Shopping", new DateTime(2024, 12, 07)),
                    new Event("New Year's Eve Fireworks", "Entertainment", new DateTime(2024, 12, 31)),
                    new Event("Winter Carnival", "Recreation", new DateTime(2024, 01, 20)),
                    new Event("Valentine's Day Dance", "Entertainment", new DateTime(2024, 02, 14)),
                    new Event("St. Patrick's Day Parade", "Cultural", new DateTime(2024, 03, 17)),
                    new Event("Easter Egg Hunt", "Family", new DateTime(2024, 03, 31)),
                    new Event("Earth Day Clean-up", "Environment", new DateTime(2024, 04, 22)),
                    new Event("Mother's Day Brunch", "Food", new DateTime(2024, 05, 12)),
                    new Event("Father's Day Barbecue", "Food", new DateTime(2024, 06, 16)),
                    new Event("Independence Day Celebration", "Cultural", new DateTime(2024, 07, 04)),
                    new Event("Summer Music Series", "Music", new DateTime(2024, 07, 13)),
                    new Event("Back to School Fair", "Education", new DateTime(2024, 08, 24)),
                    new Event("Labor Day Picnic", "Recreation", new DateTime(2024, 09, 02)),
                    new Event("Oktoberfest", "Cultural", new DateTime(2024, 09, 21)),
                    new Event("Pumpkin Carving Contest", "Art", new DateTime(2024, 10, 26)),
                    new Event("Veterans Day Ceremony", "Cultural", new DateTime(2024, 11, 11)),
                    new Event("Thanksgiving Community Dinner", "Food", new DateTime(2024, 11, 28)),
                    new Event("Tree Lighting Ceremony", "Cultural", new DateTime(2024, 12, 01)),
                    new Event("Ice Skating Rink Opening", "Recreation", new DateTime(2024, 12, 15)),
                    new Event("Flower Show", "Nature", new DateTime(2024, 05, 25)),
                    new Event("Tech Conference", "Technology", new DateTime(2024, 06, 08)),
                    new Event("Antique Fair", "Shopping", new DateTime(2024, 07, 27)),
                    new Event("Kite Flying Festival", "Recreation", new DateTime(2024, 08, 10)),
                    new Event("Salsa Dancing Night", "Entertainment", new DateTime(2024, 10, 19)),
                    new Event("Gingerbread House Competition", "Art", new DateTime(2024, 12, 14)),
                    new Event("Volunteer Appreciation Dinner", "Community", new DateTime(2024, 04, 20)),
                    new Event("Job Fair", "Career", new DateTime(2024, 05, 15)),
                    new Event("Pet Adoption Day", "Community", new DateTime(2024, 06, 29)),
                    new Event("Historical Reenactment", "Education", new DateTime(2024, 07, 13)),
                    new Event("Farmers' Appreciation Day", "Community", new DateTime(2024, 08, 31)),
                    new Event("International Food Festival", "Cultural", new DateTime(2024, 09, 28)),
                    new Event("Senior Citizens' Ball", "Community", new DateTime(2024, 10, 12)),
                    new Event("Youth Sports Tournament", "Sports", new DateTime(2024, 11, 02)),


                     new Event("Virtual Reality Experience", "Technology", new DateTime(2024, 12, 01)),
    new Event("Dungeons & Dragons Night", "Games", new DateTime(2024, 11, 03)),
    new Event("Interactive Storytelling", "Education", new DateTime(2024, 10, 17)),
    new Event("Bird Watching Tour", "Recreation", new DateTime(2024, 11, 25)),
    new Event("Debate Club Meeting", "Community", new DateTime(2024, 12, 07)),
    new Event("Street Art Tour", "Art", new DateTime(2024, 10, 19)),
    new Event("Startup Pitch Night", "Business", new DateTime(2024, 11, 09)),
    new Event("VR Game Tournament", "Technology", new DateTime(2024, 12, 16)),
    new Event("Historic Walk", "Community", new DateTime(2024, 10, 21)),
    new Event("Craft Fair", "Lifestyle", new DateTime(2024, 11, 13)),
    new Event("Climate Change Workshop", "Education", new DateTime(2024, 12, 10)),
    new Event("Jazz Night", "Music", new DateTime(2024, 10, 31)),
    new Event("Entrepreneur Networking", "Business", new DateTime(2024, 11, 24)),
    new Event("Paint and Sip", "Art", new DateTime(2024, 12, 02)),
    new Event("Volleyball Tournament", "Sports", new DateTime(2024, 10, 12)),
    new Event("Nature Photography Workshop", "Art", new DateTime(2024, 11, 26)),
    new Event("Cultural Festival", "Community", new DateTime(2024, 12, 14)),
    new Event("Public Speaking Seminar", "Education", new DateTime(2024, 10, 20)),
    new Event("Martial Arts Demonstration", "Sports", new DateTime(2024, 11, 18)),
    new Event("Folk Music Festival", "Music", new DateTime(2024, 12, 08)),
    new Event("Maker Faire", "Technology", new DateTime(2024, 10, 22)),
    new Event("Calligraphy Workshop", "Art", new DateTime(2024, 11, 21)),
    new Event("Startup Weekend", "Business", new DateTime(2024, 12, 03)),
    new Event("Urban Gardening", "Lifestyle", new DateTime(2024, 10, 15)),
    new Event("Farmers Market", "Food", new DateTime(2024, 11, 16)),
    new Event("Skateboard Competition", "Recreation", new DateTime(2024, 12, 05)),
    new Event("Interior Design Workshop", "Lifestyle", new DateTime(2024, 10, 13)),
    new Event("Coding Hackathon", "Technology", new DateTime(2024, 11, 07)),
    new Event("Talent Show", "Entertainment", new DateTime(2024, 12, 18)),
    new Event("DIY Electronics Workshop", "Education", new DateTime(2024, 10, 26)),
    new Event("Rock Climbing Adventure", "Sports", new DateTime(2024, 11, 20)),
    new Event("Afrobeat Dance Class", "Music", new DateTime(2024, 12, 09)),
    new Event("Costume Party", "Entertainment", new DateTime(2024, 10, 29)),
    new Event("Urban Exploration", "Recreation", new DateTime(2024, 11, 19)),
    new Event("Yoga in the Park", "Health", new DateTime(2024, 12, 06)),
    new Event("Anime Convention", "Entertainment", new DateTime(2024, 10, 17)),

    new Event("Drone Racing Championship", "Technology", new DateTime(2024, 03, 23)),
    new Event("Vintage Vinyl Fair", "Music", new DateTime(2024, 04, 06)),
    new Event("Stargazing Night", "Science", new DateTime(2024, 05, 18)),
    new Event("Urban Sketching Workshop", "Art", new DateTime(2024, 06, 01)),
    new Event("Beekeeping Seminar", "Education", new DateTime(2024, 07, 13)),
    new Event("Escape Room Challenge", "Entertainment", new DateTime(2024, 08, 24)),
    new Event("Sustainable Living Expo", "Environment", new DateTime(2024, 09, 07)),
    new Event("Cosplay Convention", "Entertainment", new DateTime(2024, 10, 19)),
    new Event("Chili Cook-Off", "Food", new DateTime(2024, 11, 09)),
    new Event("Ice Sculpture Festival", "Art", new DateTime(2024, 12, 21)),
    new Event("Lunar New Year Celebration", "Cultural", new DateTime(2024, 02, 10)),
    new Event("Graffiti Art Competition", "Art", new DateTime(2024, 05, 04)),
    new Event("Retro Gaming Tournament", "Games", new DateTime(2024, 06, 15)),
    new Event("Farmers' Skills Competition", "Community", new DateTime(2024, 07, 20)),
    new Event("Silent Disco Party", "Entertainment", new DateTime(2024, 08, 31)),
    new Event("Origami Workshop", "Art", new DateTime(2024, 09, 14)),
    new Event("Haunted House Experience", "Entertainment", new DateTime(2024, 10, 27)),
    new Event("Ugly Sweater Contest", "Entertainment", new DateTime(2024, 12, 13)),
    new Event("Winter Sports Expo", "Sports", new DateTime(2024, 01, 27)),
    new Event("Chocolate Festival", "Food", new DateTime(2024, 02, 17)),
    new Event("Kite Making Workshop", "Recreation", new DateTime(2024, 03, 30)),
    new Event("Cherry Blossom Festival", "Cultural", new DateTime(2024, 04, 13)),
    new Event("Rooftop Yoga Session", "Health", new DateTime(2024, 05, 11)),
    new Event("Storytelling Night", "Entertainment", new DateTime(2024, 06, 22)),
    new Event("Sandcastle Building Contest", "Recreation", new DateTime(2024, 07, 06)),
    new Event("Meteor Shower Viewing Party", "Science", new DateTime(2024, 08, 12)),
    new Event("Upcycling Craft Fair", "Lifestyle", new DateTime(2024, 09, 21)),
    new Event("Pumpkin Pie Eating Contest", "Food", new DateTime(2024, 10, 12)),
    new Event("Lantern Festival", "Cultural", new DateTime(2024, 11, 23)),
    new Event("Polar Bear Plunge", "Recreation", new DateTime(2024, 01, 01)),
    new Event("Bubble Tea Festival", "Food", new DateTime(2024, 05, 25)),
    new Event("Lego Building Competition", "Games", new DateTime(2024, 07, 27)),
    new Event("Air Guitar Championship", "Entertainment", new DateTime(2024, 08, 17)),
    new Event("Mushroom Foraging Expedition", "Nature", new DateTime(2024, 09, 28)),
    new Event("Steampunk Convention", "Entertainment", new DateTime(2024, 10, 05)),
    new Event("Beard and Mustache Competition", "Entertainment", new DateTime(2024, 11, 16)),
    new Event("Ugly Dog Contest", "Entertainment", new DateTime(2024, 06, 29)),
    new Event("Bubble Soccer Tournament", "Sports", new DateTime(2024, 07, 13)),
    new Event("Tiny House Exhibition", "Lifestyle", new DateTime(2024, 08, 03)),
    new Event("Neon Night Run", "Sports", new DateTime(2024, 09, 14)),
    new Event("Cheese Rolling Contest", "Recreation", new DateTime(2024, 05, 27)),
    new Event("Extreme Ironing Competition", "Sports", new DateTime(2024, 06, 08)),
    new Event("Cardboard Boat Race", "Recreation", new DateTime(2024, 07, 20)),
    new Event("Human Chess Match", "Games", new DateTime(2024, 08, 10)),
    new Event("Zombie Walk", "Entertainment", new DateTime(2024, 10, 26)),
    new Event("Rubik's Cube Speed Solving Contest", "Games", new DateTime(2024, 11, 09)),
    new Event("Augmented Reality Art Exhibition", "Art", new DateTime(2024, 09, 07)),
    new Event("Soap Box Derby", "Recreation", new DateTime(2024, 06, 15)),
    new Event("Extreme Pogo Stick Competition", "Sports", new DateTime(2024, 07, 27)),
    new Event("Miniature Art Show", "Art", new DateTime(2024, 08, 24)),

    //these for search 

  new Event("Tech Summit", "Technology", new DateTime(2024, 11, 15)),
new Event("AI Innovations Expo", "Artificial Intelligence", new DateTime(2025, 03, 20)),
new Event("Blockchain Conference", "Finance", new DateTime(2025, 06, 14)),
new Event("Robotics World", "Engineering", new DateTime(2024, 12, 05)),
new Event("Cybersecurity Forum", "Technology", new DateTime(2025, 04, 18)),
new Event("Space Exploration Symposium", "Science", new DateTime(2025, 07, 10)),
new Event("Quantum Computing Meetup", "Technology", new DateTime(2024, 12, 22)),
new Event("Climate Change Seminar", "Environment", new DateTime(2025, 02, 10)),
new Event("Renewable Energy Expo", "Energy", new DateTime(2025, 05, 02)),
new Event("Medical Tech Innovations", "Healthcare", new DateTime(2024, 11, 25)),
new Event("Big Data Conference", "Data Science", new DateTime(2025, 03, 05)),
new Event("Internet of Things Symposium", "Technology", new DateTime(2024, 12, 16)),
new Event("Biotech Forum", "Biotechnology", new DateTime(2025, 06, 28)),
new Event("Sustainability Summit", "Environment", new DateTime(2025, 08, 14)),
new Event("Artificial Intelligence Ethics Conference", "AI", new DateTime(2025, 09, 12)),
new Event("Nanotechnology Expo", "Engineering", new DateTime(2024, 11, 20)),
new Event("Self-Driving Cars Summit", "Automotive", new DateTime(2025, 02, 19)),
new Event("Agricultural Innovations Expo", "Agriculture", new DateTime(2025, 03, 25)),
new Event("Virtual Reality Conference", "Technology", new DateTime(2025, 06, 06)),
new Event("Autonomous Systems Symposium", "Engineering", new DateTime(2025, 07, 17)),
new Event("Space Tech Innovations", "Aerospace", new DateTime(2025, 04, 24)),
new Event("Environmental Science Conference", "Environment", new DateTime(2025, 09, 25)),
new Event("Genomics Expo", "Healthcare", new DateTime(2024, 12, 14)),
new Event("Hydrogen Energy Summit", "Energy", new DateTime(2025, 05, 19)),
new Event("Cryptocurrency Forum", "Finance", new DateTime(2025, 02, 03)),
new Event("AI in Healthcare Conference", "Healthcare", new DateTime(2025, 03, 08)),
new Event("Smart Cities Symposium", "Urban Development", new DateTime(2025, 06, 20)),
new Event("Clean Energy Conference", "Environment", new DateTime(2025, 07, 25)),
new Event("Machine Learning Workshop", "Artificial Intelligence", new DateTime(2024, 11, 30)),
new Event("Healthcare Data Analytics", "Healthcare", new DateTime(2025, 02, 28)),
new Event("Sustainable Agriculture Summit", "Agriculture", new DateTime(2025, 03, 15)),
new Event("Quantum Physics Conference", "Science", new DateTime(2025, 06, 08)),
new Event("Energy Storage Expo", "Energy", new DateTime(2025, 07, 12)),
new Event("Biotech Innovations Forum", "Biotechnology", new DateTime(2025, 08, 22)),
new Event("AI in Finance Summit", "Finance", new DateTime(2025, 04, 02)),
new Event("3D Printing Conference", "Technology", new DateTime(2024, 12, 01)),
new Event("Renewable Resources Expo", "Energy", new DateTime(2025, 05, 08)),
new Event("Data Science Forum", "Data Science", new DateTime(2025, 02, 12)),
new Event("Autonomous Vehicles Symposium", "Automotive", new DateTime(2025, 06, 04)),
new Event("Green Energy Innovations", "Energy", new DateTime(2025, 07, 30)),
new Event("Augmented Reality Conference", "Technology", new DateTime(2024, 12, 18)),
new Event("Marine Science Symposium", "Science", new DateTime(2025, 03, 12)),
new Event("Artificial Intelligence in Retail", "AI", new DateTime(2025, 06, 18)),
new Event("Telemedicine Innovations", "Healthcare", new DateTime(2025, 07, 05)),
new Event("Energy Efficiency Conference", "Environment", new DateTime(2025, 08, 30)),
new Event("Food Science Expo", "Agriculture", new DateTime(2024, 11, 10)),
new Event("Industrial Automation Forum", "Engineering", new DateTime(2025, 03, 22)),
new Event("Healthcare Innovations Summit", "Healthcare", new DateTime(2025, 06, 24)),
new Event("FinTech Forum", "Finance", new DateTime(2025, 07, 15)),
new Event("Sustainable Engineering Symposium", "Engineering", new DateTime(2025, 08, 02)),
new Event("Digital Health Conference", "Healthcare", new DateTime(2024, 12, 08)),
new Event("Oceanography Conference", "Science", new DateTime(2025, 05, 06)),
new Event("AI for Social Good", "AI", new DateTime(2025, 09, 09)),
new Event("Energy Transition Summit", "Energy", new DateTime(2025, 02, 23)),
new Event("Biotech in Agriculture", "Biotechnology", new DateTime(2025, 03, 27)),
new Event("Green Technology Expo", "Environment", new DateTime(2025, 06, 30)),
new Event("Smart Transportation Summit", "Automotive", new DateTime(2025, 07, 18)),
new Event("Digital Transformation Forum", "Technology", new DateTime(2025, 08, 25)),
new Event("Precision Medicine Conference", "Healthcare", new DateTime(2025, 04, 11)),
new Event("Sustainable Urban Development", "Urban Development", new DateTime(2025, 05, 15)),
new Event("Clean Energy Innovations", "Energy", new DateTime(2025, 06, 22)),
new Event("Future of Transportation", "Technology", new DateTime(2025, 08, 07)),
new Event("Agriculture 4.0 Expo", "Agriculture", new DateTime(2025, 09, 02)),
new Event("Quantum Materials Symposium", "Science", new DateTime(2025, 07, 06)),
new Event("Bioinformatics Conference", "Biotechnology", new DateTime(2025, 02, 17)),
new Event("AI and Robotics Expo", "Technology", new DateTime(2025, 03, 18)),
new Event("Environmental Protection Conference", "Environment", new DateTime(2025, 04, 15)),
new Event("Energy Future Forum", "Energy", new DateTime(2025, 05, 20)),
new Event("Health Tech Innovations", "Healthcare", new DateTime(2025, 06, 12)),
new Event("Climate Tech Expo", "Environment", new DateTime(2025, 07, 29)),
new Event("AI in Marketing", "AI", new DateTime(2025, 08, 09)),
new Event("Space Tech Conference", "Aerospace", new DateTime(2025, 09, 07)),
new Event("Autonomous Robotics Summit", "Engineering", new DateTime(2024, 12, 10)),
new Event("Blockchain in Healthcare", "Finance", new DateTime(2025, 04, 03)),
new Event("Digital Farming Expo", "Agriculture", new DateTime(2025, 05, 25)),
new Event("Green Building Innovations", "Urban Development", new DateTime(2025, 07, 13)),
new Event("Self-Sustaining Energy", "Energy", new DateTime(2025, 08, 15)),
new Event("Neuroscience Innovations", "Healthcare", new DateTime(2024, 11, 06)),
new Event("AI in Education Forum", "Education", new DateTime(2025, 03, 14)),
new Event("Renewable Power Forum", "Energy", new DateTime(2025, 05, 05)),
new Event("Data Privacy Symposium", "Technology", new DateTime(2025, 06, 03)),
new Event("AI for Medicine", "Healthcare", new DateTime(2025, 08, 17)),
new Event("Urban Sustainability Conference", "Environment", new DateTime(2025, 09, 29)),
new Event("AI and Ethics Forum", "AI", new DateTime(2025, 04, 12)),
new Event("Energy Conservation Symposium", "Environment", new DateTime(2025, 06, 15)),
new Event("Next-Gen Healthcare", "Healthcare", new DateTime(2025, 07, 07)),
new Event("Transportation Tech Summit", "Automotive", new DateTime(2025, 08, 10)),
new Event("Quantum Sensors Expo", "Technology", new DateTime(2024, 12, 09)),
new Event("Bioengineering Innovations", "Biotechnology", new DateTime(2025, 03, 02)),
new Event("Circular Economy Forum", "Environment", new DateTime(2025, 04, 29)),
new Event("Water Conservation Expo", "Environment", new DateTime(2025, 05, 28)),
new Event("Smart Energy Solutions", "Energy", new DateTime(2025, 07, 19)),
new Event("Sustainable Agriculture Conference", "Agriculture", new DateTime(2025, 08, 26)),
new Event("Environmental Technology Expo", "Environment", new DateTime(2025, 06, 19)),
new Event("AI and Law Symposium", "Artificial Intelligence", new DateTime(2025, 09, 15)),
new Event("Genetic Engineering Forum", "Biotechnology", new DateTime(2025, 02, 11)),
new Event("Smart Homes Innovations", "Technology", new DateTime(2025, 05, 13)),
new Event("Digital Manufacturing Conference", "Engineering", new DateTime(2025, 07, 16)),
new Event("AI for Business Innovations", "Artificial Intelligence", new DateTime(2025, 08, 04)),
new Event("Clean Water Technologies", "Environment", new DateTime(2025, 09, 19))





            };
        }
    }
}
